name: Hive - GraphQL
on:
    schedule:
        - cron: "15 03 * * *"

env:
    GOPROXY: "${{ vars.GOPROXY }}"
    S3_BUCKET: hive-results
    S3_PATH: generic
    S3_PUBLIC_URL: https://hive.ethpandaops.io/#/test/generic/
    INSTALL_RCLONE_VERSION: v1.68.2
    GLOBAL_EXTRA_FLAGS: >-
        --client.checktimelimit=180s
        --sim.parallelism=4
        --docker.auth
        --docker.buildoutput
    GRAPHQL_FLAGS: >-
        --sim.loglevel=3

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            hive_repo: ${{ steps.client_config_schedule.outputs.hive_repo }}
            hive_tag: ${{ steps.client_config_schedule.outputs.hive_tag }}
            client_config: ${{ steps.client_config_schedule.outputs.client_config }}
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - uses: ethpandaops/hive-github-action/helpers/client-config@1aa8d73dad34de13afbb3113ab16c1a462d2fbc3 # v0.5.0
              name: "Client config: schedule"
              id: client_config_schedule
              with:
                  client_source: "git"
                  hive_version: "ethereum/hive@master"
                  goproxy: ${{ env.GOPROXY }}

    test:
        timeout-minutes: 240 # 4 hours
        needs: prepare
        runs-on: [self-hosted-ghr-custom, size-l-x64]
        concurrency:
            group: hive-graphql-${{ matrix.client }}-${{ github.run_id }}
        strategy:
            fail-fast: false
            matrix:
                # GraphQL is only supported by besu and go-ethereum
                client:
                    - besu
                    - go-ethereum
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - uses: ethpandaops/actions/docker-login@a91b7a8dd6a264f5e845ac2aa52d2d6f24e6d01d
              with:
                  username: ethpandaops
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - uses: ethpandaops/hive-github-action/helpers/self-hosted-runner-dependencies@1aa8d73dad34de13afbb3113ab16c1a462d2fbc3 # v0.5.0
              if: runner.environment != 'github-hosted'

            - uses: ethpandaops/hive-github-action@1aa8d73dad34de13afbb3113ab16c1a462d2fbc3 # v0.5.0
              with:
                  hive_repository: ${{ needs.prepare.outputs.hive_repo }}
                  hive_version: ${{ needs.prepare.outputs.hive_tag }}
                  client: ${{ matrix.client }}
                  simulator: ethereum/graphql
                  client_config: ${{ needs.prepare.outputs.client_config }}
                  extra_flags: >-
                      ${{ env.GLOBAL_EXTRA_FLAGS }}
                      ${{ env.GRAPHQL_FLAGS }}
                  s3_upload: true
                  s3_bucket: ${{ env.S3_BUCKET }}
                  s3_path: ${{ env.S3_PATH }}
                  s3_public_url: ${{ env.S3_PUBLIC_URL }}
                  rclone_config: ${{ secrets.HIVE_RCLONE_CONFIG }}
                  rclone_version: ${{ env.INSTALL_RCLONE_VERSION }}
                  workflow_artifact_upload: true
                  website_upload: true
