name: ethereum/consensus (legacy)
on:
  workflow_dispatch:
  schedule:
    - cron: "45 05 */4 * *" # Every 4th day at 05:45 UTC

jobs:
  trigger-generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'generic.yaml',
              ref: 'master',
              inputs: {
                simulator: '"ethereum/consensus"',
                extra_flags: '--sim.limit=legacy/',
                concurrency_group: 'legacy'
              }
            });
