name: ethereum/consensus (consensus)
on:
  workflow_dispatch:
  schedule:
    - cron: "10 01 */2 * *" # Every 2nd day at 01:10 UTC

jobs:
  trigger-generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'generic.yaml',
              ref: 'main',
              inputs: {
                simulator: 'ethereum/consensus',
                extra_flags: '--sim.limit=consensus/'
              }
            });
