name: ethereum/eels/consume-rlp (eels/consume-rlp)
on:
  workflow_dispatch:
  schedule:
    - cron: "15 05 * * 2" # Every second day at 05:15 UTC

jobs:
  trigger-generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'generic.yaml',
              ref: 'master',
              inputs: {
                simulator: '["ethereum/eels/consume-rlp"]',
                concurrency_group: 'eels-consume-rlp',
                timeout_minutes: '2880'
              }
            });
