name: Hive - Sync
on:
    schedule:
        - cron: "15 03 * * *" # Run 1 hour after main workflow
    workflow_dispatch:
        inputs:
            clients:
                type: string
                default: "go-ethereum,besu,reth,nethermind,erigon,nimbus-el,ethrex"
                description: Comma-separated list of clients to test (all clients run together)
            hive_version:
                type: string
                default: ethereum/hive@master
                description: GitHub repository and tag for hive (repo@tag)
            client_source:
                type: choice
                description: >-
                    How client images should be sourced.
                    'git' will use the github repo and tag (See client_repos).
                    'docker' will use the docker registry and tag (See client_images).
                options:
                    - docker
                    - git
            client_repos:
                type: string
                default: |
                    {
                      "geth": "ethereum/go-ethereum@master",
                      "besu": "hyperledger/besu@main",
                      "reth": "paradigmxyz/reth@main",
                      "nethermind": "NethermindEth/nethermind@master",
                      "erigon": "erigontech/erigon@main",
                      "nimbusel": "status-im/nimbus-eth1@master",
                      "ethrex": "lambdaclass/ethrex@main"
                    }
                description: 'JSON object containing client versions in format {"client": "repo@tag", ...}'
            client_images:
                type: string
                default: |
                    {
                      "geth": "docker.ethquokkaops.io/dh/ethpandaops/geth:master",
                      "besu": "docker.ethquokkaops.io/dh/ethpandaops/besu:main",
                      "reth": "docker.ethquokkaops.io/dh/ethpandaops/reth:main",
                      "nethermind": "docker.ethquokkaops.io/dh/ethpandaops/nethermind:master",
                      "erigon": "docker.ethquokkaops.io/dh/ethpandaops/erigon:main",
                      "nimbusel": "docker.ethquokkaops.io/dh/ethpandaops/nimbus-eth1:master",
                      "ethrex": "ghcr.io/lambdaclass/ethrex:main"
                    }
                description: 'JSON object containing client docker images in format {"client": "registry:tag", ...}'
            extra_flags:
                type: string
                default: ""
                description: Additional flags to append to the hive command
            concurrency_group:
                type: string
                default: "default"
                description: Concurrency group for the workflow
            workflow_artifact_upload:
                description: "Upload test results as an workflow artifact"
                required: false
                default: "true"

env:
    # Proxy
    GOPROXY: "${{ vars.GOPROXY }}"
    # Hive action environment variables
    S3_BUCKET: hive-results
    S3_PATH: generic
    S3_PUBLIC_URL: https://hive.ethpandaops.io/#/test/generic/
    INSTALL_RCLONE_VERSION: v1.68.2
    # Flags used for all simulators
    GLOBAL_EXTRA_FLAGS: >-
        --client.checktimelimit=180s
        --sim.parallelism=4
        --docker.auth
        --docker.buildoutput
    # Flags used for the ethereum/sync simulator
    SYNC_FLAGS: >-
        --sim.loglevel=3

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            # Hive version
            hive_repo: >-
                ${{
                  steps.client_config_schedule.outputs.hive_repo ||
                  steps.client_config_dispatch.outputs.hive_repo
                }}
            hive_tag: >-
                ${{
                  steps.client_config_schedule.outputs.hive_tag ||
                  steps.client_config_dispatch.outputs.hive_tag
                }}
            # client_config contains the YAML client config for Hive
            client_config: >-
                ${{
                  steps.client_config_schedule.outputs.client_config ||
                  steps.client_config_dispatch.outputs.client_config
                }}
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            # Scheduled runs
            - uses: ethpandaops/hive-github-action/helpers/client-config@1aa8d73dad34de13afbb3113ab16c1a462d2fbc3 # v0.5.0
              if: github.event_name == 'schedule'
              name: "Client config: schedule"
              id: client_config_schedule
              with:
                  client_source: "git"
                  hive_version: "ethereum/hive@master"
                  goproxy: ${{ env.GOPROXY }}

            # Manual dispatch
            - uses: ethpandaops/hive-github-action/helpers/client-config@1aa8d73dad34de13afbb3113ab16c1a462d2fbc3 # v0.5.0
              if: github.event_name == 'workflow_dispatch'
              name: "Client config: dispatch"
              id: client_config_dispatch
              with:
                  client_repos: ${{ inputs.client_repos }}
                  client_images: ${{ inputs.client_images }}
                  client_source: ${{ inputs.client_source }}
                  hive_version: ${{ inputs.hive_version }}
                  goproxy: ${{ env.GOPROXY }}

    test:
        timeout-minutes: 1440 # 24 hours
        needs: prepare
        runs-on: [self-hosted-ghr, size-xl-x64]
        concurrency:
            group: >-
                ${{ github.head_ref || inputs.concurrency_group }}-sync
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - uses: ethpandaops/actions/docker-login@a91b7a8dd6a264f5e845ac2aa52d2d6f24e6d01d
              with:
                  username: ethpandaops
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - uses: ethpandaops/hive-github-action/helpers/self-hosted-runner-dependencies@1aa8d73dad34de13afbb3113ab16c1a462d2fbc3 # v0.5.0
              if: runner.environment != 'github-hosted'

            - uses: ethpandaops/hive-github-action@1aa8d73dad34de13afbb3113ab16c1a462d2fbc3 # v0.5.0
              with:
                  hive_repository: ${{ needs.prepare.outputs.hive_repo }}
                  hive_version: ${{ needs.prepare.outputs.hive_tag }}
                  # All clients passed together - the sync simulator handles the matrix internally
                  client: ${{ inputs.clients || 'go-ethereum,besu,reth,nethermind,erigon,nimbus-el,ethrex' }}
                  simulator: ethereum/sync
                  client_config: ${{ needs.prepare.outputs.client_config }}
                  extra_flags: >-
                      ${{ env.GLOBAL_EXTRA_FLAGS }}
                      ${{ env.SYNC_FLAGS }}
                      ${{ inputs.extra_flags }}
                  s3_upload: true
                  s3_bucket: ${{ env.S3_BUCKET }}
                  s3_path: ${{ env.S3_PATH }}
                  s3_public_url: ${{ env.S3_PUBLIC_URL }}
                  rclone_config: ${{ secrets.HIVE_RCLONE_CONFIG }}
                  rclone_version: ${{ env.INSTALL_RCLONE_VERSION }}
                  workflow_artifact_upload: ${{ inputs.workflow_artifact_upload }}
                  website_upload: true
